server:
  port: 8080

spring:
  application:
    name: KIRANAPP-API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Gateway routes
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: shipping-service
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/shipping/**
